# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.3.0
_src_path: https://github.com/napari/napari-plugin-template
display_name: Vizsla
email: github@tamasnagy.com
full_name: Tamas Nagy
github_repository_url: provide later
github_username_or_organization: tlnagy
include_reader_plugin: false
include_sample_data_plugin: false
include_widget_plugin: true
include_writer_plugin: false
install_dependabot: true
install_precommit: true
license: MIT
module_name: napari_vizsla
plugin_name: napari-vizsla
short_description: Your friendly tracking assistant. Sniff out and fix broken tracks.
